import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { waitForVisualSettling } from "./visual-settling";

test("独立检索配置、凭据脱敏、窄屏表单与向量索引", async ({ page, request }) => {
  await page.goto("/settings");
  await page.getByRole("button", { name: "配置资料查找", exact: true }).click();
  await page.getByText("如何获取硅基流动 API Key？查看逐步教程", { exact: true }).click();
  await expect(page.getByRole("link", { name: "打开 API 密钥管理", exact: true })).toHaveAttribute("href", "https://cloud.siliconflow.cn/account/ak");
  await expect(page.getByText("先完成实名认证", { exact: true })).toBeVisible();
  await page.getByLabel("资料查找 API 地址", { exact: true }).fill("http://127.0.0.1:3301");
  await page.getByLabel("语义查找模型", { exact: true }).fill("audit-embedding");
  await page.getByLabel("相关性筛选模型", { exact: true }).fill("audit-reranker");
  await page.getByLabel("资料查找 API Key", { exact: true }).fill("retrieval-e2e-fixture");
  await page.getByRole("switch", { name: "按意思查找相关资料", exact: true }).click();
  await expect(page.getByLabel("语义查找模型", { exact: true })).toHaveValue("audit-embedding");
  await expect(page.getByLabel("资料查找 API Key", { exact: true })).toHaveValue("retrieval-e2e-fixture");
  await page.setViewportSize({ width: 390, height: 844 });
  await waitForVisualSettling(page);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations.map(item => item.id)).toEqual([]);
  await page.screenshot({ path: "test-results/retrieval-form-mobile.png", fullPage: true });
  await page.getByRole("button", { name: "保存查找配置", exact: true }).click();
  await expect(page.getByText("已开启按意思查找", { exact: true })).toBeVisible();
  const configured = (await (await request.get("/api/settings")).json()).data.settings.retrievalModel;
  expect(configured.hasApiKey).toBe(true); expect(JSON.stringify(configured)).not.toContain("retrieval-e2e-fixture");
  await page.getByRole("button", { name: "检查查找连接", exact: true }).click();
  await expect(page.getByText("语义查找与相关性筛选服务连接正常。", { exact: true })).toBeVisible();
  await expect.poll(async () => (await (await request.get("/api/settings/retrieval")).json()).data.pending).toBe(0);
  await page.getByRole("button", { name: "配置资料查找", exact: true }).click();
  await expect(page.getByLabel("资料查找 API Key", { exact: true })).toHaveValue("");
  await page.getByRole("button", { name: "取消", exact: true }).click();
  const { hasApiKey: _key, ...input } = configured;
  await request.patch("/api/settings", { data: { retrievalModel: { ...input, enabled: false, clearApiKey: true } } });
});
