import { test, expect } from '@playwright/test';
import { assertHtmlIsolation } from './html-isolation';
import AxeBuilder from '@axe-core/playwright';
import { waitForVisualSettling } from './visual-settling';

test('HTML 问答：等待、选择记忆、隔离交互、全屏与下载', async ({ page, request }) => {
  await request.patch('/api/settings', { data: { providers: [{ id: 'html-fixture', label: '本地测试模型', baseUrl: 'http://127.0.0.1:3301', apiKey: '', model: 'audit-model', reasoningEffort: 'high', contextWindow: 32768 }], activeProviderId: 'html-fixture', preferSavedModels: true } });
  const files = await request.get('/api/pages');
  if (!(await files.json()).data.pages?.length) {
    const ingest = await request.post('/api/ingest', { multipart: { file: { name: 'html-fixture.md', mimeType: 'text/markdown', buffer: Buffer.from('推荐算法用于预测用户偏好。协同过滤分为基于用户与基于物品两类。') } } });
    const ingestData = (await ingest.json()).data;
    const jobId = ingestData.jobId ?? ingestData.id;
    await expect.poll(async () => (await (await request.get(`/api/jobs/${jobId}`)).json()).data.status, { timeout: 20000 }).toBe('awaiting_review');
    const staged = (await (await request.get(`/api/jobs/${jobId}`)).json()).data.draft;
    const committed = await request.post(`/api/ingest/${jobId}/commit`, { data: { draft: staged.draft } });
    expect(committed.ok()).toBe(true);
  }
  await page.setViewportSize({ width: 1366, height: 900 });
  await page.goto('/chat');
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const htmlButton = page.getByRole('button', { name: '生成交互阅读页', exact: true });
  await expect(htmlButton).toBeEnabled();
  await expect(page.getByText('仅根据已入库资料回答')).toHaveCount(0);
  await htmlButton.hover(); await expect(page.getByRole('tooltip')).toBeVisible();
  await htmlButton.click(); await expect(htmlButton).toHaveAttribute('aria-pressed', 'true');
  await expect(htmlButton).toHaveCSS('outline-style', 'none');
  const effortButton = page.getByRole('button', { name: /选择问答思考强度/ });
  await effortButton.click();
  const effortPicker = page.getByRole('group', { name: '问答思考强度', exact: true });
  await expect(effortPicker.getByRole('button', { name: '思考 · 高', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await waitForVisualSettling(page);
  await page.screenshot({ path: 'test-results/chat-effort-desktop.png', fullPage: true });
  await effortPicker.getByRole('button', { name: '思考 · 低', exact: true }).click();
  await page.getByRole('button', { name: /选择问答模型/ }).click();
  await expect(page.getByLabel('搜索模型', { exact: true })).toHaveCount(0);
  await expect(page.getByText('手动填写与上下文容量', { exact: true })).toHaveCount(0);
  await page.keyboard.press('ArrowDown');
  await expect(page.getByRole('button', { name: 'audit-fast', exact: true })).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(effortButton).toContainText('思考 · 高');
  await effortButton.click();
  await effortPicker.getByRole('button', { name: '思考 · 低', exact: true }).click();
  await page.getByLabel('向知识库提问').fill('推荐算法 HTML_WAIT');
  await page.getByRole('button', { name: '开始提问', exact: true }).click();
  await expect(page).toHaveURL(/\/chat\?s=[0-9A-Z]+/);
  await expect(page.getByTestId('chat-waiting')).toBeVisible();
  await expect(page.locator('.ai-working[data-working-tone="answer"]')).toBeVisible();
  await expect(page.getByText(/已等待 \d+ 秒/)).toBeVisible();
  await expect(page.getByText('查看检索过程')).toHaveCount(0);
  await page.screenshot({ path: 'test-results/chat-html-desktop-waiting.png', fullPage: true });
  await page.reload();
  await expect(page.getByTestId('chat-artifact')).toBeVisible({ timeout: 20000 });
  await expect(page.getByTestId('chat-waiting')).toBeHidden();
  const citation = page.locator('main sup.citation-ref[data-citation="1"]');
  await expect(citation).toHaveText('1');
  await expect(page.locator('main .prose-weave')).not.toContainText('[ID:');
  await citation.focus();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toBeHidden();
  const frame = page.frameLocator('iframe[title="回答图解.html · 预览"]');
  await expect(frame.getByRole('heading', { name: '推荐算法，如何理解你？' })).toBeVisible();
  await expect(frame.locator('sup[data-citation="1"]')).toHaveText('1');
  await expect(frame.locator('p').first()).not.toContainText('[ID:');
  await frame.getByRole('link', { name: /^引用 1：/ }).click();
  await expect(frame.locator('#weave-source-1')).toBeInViewport();
  await frame.getByRole('button', { name: '展开图解' }).click();
  await expect(frame.locator('#detail')).toBeVisible();
  await expect(page.locator('iframe').first()).toHaveAttribute('sandbox', 'allow-scripts');
  await assertHtmlIsolation(page, 'iframe[title="回答图解.html · 预览"]');
  await page.screenshot({ path: 'test-results/chat-html-desktop-ready.png', fullPage: true });
  await page.getByRole('button', { name: '全屏阅读', exact: true }).click();
  await expect(page.getByRole('dialog', { name: '全屏阅读 回答图解.html' })).toBeVisible();
  const fullscreen = page.frameLocator('iframe[title="回答图解.html · 全屏阅读"]');
  await fullscreen.getByRole('button', { name: '展开图解' }).focus(); await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toBeHidden();
  await expect(page.getByRole('button', { name: '全屏阅读', exact: true })).toBeFocused();
  const download = page.waitForEvent('download'); await page.getByRole('link', { name: '下载 HTML', exact: true }).click();
  expect((await download).suggestedFilename()).toBe('回答图解.html');
  const id = new URL(page.url()).searchParams.get('s')!;
  const saved = (await (await request.get(`/api/chat/sessions/${id}`)).json()).data;
  expect(saved.session.config).toMatchObject({ model: 'audit-fast', reasoningEffort: 'low', showMe: true, contextWindow: 16384 });
  expect(saved.messages.at(-1).timings.firstTextMs).toBeGreaterThanOrEqual(1500);
  expect(saved.messages.at(-1).content).not.toContain('<html');
  await page.goto('/chat'); await expect(htmlButton).toHaveAttribute('aria-pressed', 'false');
  await expect(effortButton).toContainText('思考 · 高');
  await page.goto(`/chat?s=${id}`); await expect(htmlButton).toHaveAttribute('aria-pressed', 'true');
  await expect(frame.getByRole('heading', { name: '推荐算法，如何理解你？' })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' });
  await expect.poll(() => page.evaluate(() => document.documentElement.classList.contains('dark'))).toBe(true);
  await waitForVisualSettling(page);
  await page.screenshot({ path: 'test-results/chat-html-mobile-ready.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: /选择问答模型/ }).click();
  await expect(page.getByText('正在读取模型…', { exact: true })).toBeHidden();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/chat-html-mobile-models.png', fullPage: true });
  await page.keyboard.press('Escape');
  await effortButton.click();
  await expect(effortPicker).toBeVisible();
  await waitForVisualSettling(page);
  await page.screenshot({ path: 'test-results/chat-effort-mobile.png', fullPage: true });
  await page.getByRole('button', { name: /选择问答模型/ }).click({ timeout: 5000 });
  await expect(effortPicker).toBeHidden();
  await expect(page.getByRole('group', { name: '问答模型', exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  const audit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  expect(audit.violations.map(item => ({ id: item.id, nodes: item.nodes.map(node => node.target) }))).toEqual([]);
  expect(errors).toEqual([]);
});
